// ========================================
// DEV GALÁXIAS — Mock Data
// ========================================

export const currentUser = {
  id: '1',
  name: 'Edimar Barros',
  displayName: 'Edimar',
  email: 'edimar@devgalaxias.com',
  avatarUrl: null,
  level: 12,
  title: 'Commander',
  totalXp: 4520,
  nextLevelXp: 6000,
  currentLevelXp: 3000,
  streak: 15,
  longestStreak: 22,
  experienceLevel: 'junior',
  joinedAt: '2026-01-15',
};

export const userStats = {
  tracksCompleted: 1,
  tracksInProgress: 2,
  exercisesCompleted: 87,
  projectsCompleted: 3,
  achievementsUnlocked: 14,
  avgCodeReviewScore: 76,
  totalHoursStudied: 320,
  lessonsCompleted: 68,
};

export const dailyMissions = [
  {
    id: '1',
    type: 'lesson',
    description: 'Complete a aula "Goroutines e Channels"',
    xpReward: 20,
    completed: true,
    icon: '📚',
  },
  {
    id: '2',
    type: 'exercise',
    description: 'Resolva 2 exercícios de concorrência em Go',
    xpReward: 60,
    completed: false,
    icon: '🏋️',
  },
  {
    id: '3',
    type: 'project',
    description: 'Implemente endpoint POST /users no projeto API',
    xpReward: 50,
    completed: false,
    icon: '🚀',
  },
];

export const tracks = [
  {
    id: '0',
    name: 'Fundamentos',
    slug: 'fundamentos',
    level: 0,
    description: 'Lógica, Algoritmos, Estruturas de Dados, Linux e Git',
    icon: '🌱',
    color: '#10b981',
    totalModules: 5,
    totalLessons: 40,
    totalExercises: 60,
    estimatedHours: 80,
    difficulty: 'beginner',
    progress: 100,
    status: 'completed',
    enrolled: true,
  },
  {
    id: '1',
    name: 'Go Básico',
    slug: 'go-basico',
    level: 1,
    description: 'Domine os fundamentos da linguagem Go',
    icon: '🐹',
    color: '#3b82f6',
    totalModules: 5,
    totalLessons: 40,
    totalExercises: 55,
    estimatedHours: 60,
    difficulty: 'beginner',
    progress: 65,
    status: 'in_progress',
    enrolled: true,
  },
  {
    id: '2',
    name: 'APIs REST, PostgreSQL & Docker',
    slug: 'apis-rest',
    level: 2,
    description: 'Construa APIs profissionais com banco de dados e containers',
    icon: '🌐',
    color: '#8b5cf6',
    totalModules: 5,
    totalLessons: 45,
    totalExercises: 70,
    estimatedHours: 80,
    difficulty: 'intermediate',
    progress: 12,
    status: 'in_progress',
    enrolled: true,
  },
  {
    id: '3',
    name: 'Redis, Mensageria & Arquitetura',
    slug: 'redis-mensageria',
    level: 3,
    description: 'Domine caching, mensageria e fundamentos de arquitetura',
    icon: '⚡',
    color: '#f59e0b',
    totalModules: 4,
    totalLessons: 35,
    totalExercises: 45,
    estimatedHours: 60,
    difficulty: 'intermediate',
    progress: 0,
    status: 'locked',
    enrolled: false,
  },
  {
    id: '4',
    name: 'DDD, Clean Arch, CQRS',
    slug: 'ddd-clean-arch',
    level: 4,
    description: 'Domine arquitetura de software avançada',
    icon: '🏗️',
    color: '#ec4899',
    totalModules: 4,
    totalLessons: 40,
    totalExercises: 54,
    estimatedHours: 80,
    difficulty: 'advanced',
    progress: 0,
    status: 'locked',
    enrolled: false,
  },
  {
    id: '5',
    name: 'Kubernetes, Cloud & Observabilidade',
    slug: 'kubernetes-cloud',
    level: 5,
    description: 'Deploy, cloud e operações de sistemas distribuídos',
    icon: '☸️',
    color: '#06b6d4',
    totalModules: 4,
    totalLessons: 45,
    totalExercises: 50,
    estimatedHours: 80,
    difficulty: 'advanced',
    progress: 0,
    status: 'locked',
    enrolled: false,
  },
  {
    id: '6',
    name: 'Next.js',
    slug: 'nextjs',
    level: 6,
    description: 'Construa aplicações web modernas com Next.js',
    icon: '⚛️',
    color: '#a78bfa',
    totalModules: 5,
    totalLessons: 35,
    totalExercises: 40,
    estimatedHours: 60,
    difficulty: 'intermediate',
    progress: 0,
    status: 'locked',
    enrolled: false,
  },
  {
    id: '7',
    name: 'Flutter',
    slug: 'flutter',
    level: 7,
    description: 'Construa apps móveis multiplataforma com Flutter',
    icon: '📱',
    color: '#3b82f6',
    totalModules: 5,
    totalLessons: 40,
    totalExercises: 45,
    estimatedHours: 70,
    difficulty: 'intermediate',
    progress: 0,
    status: 'locked',
    enrolled: false,
  },
  {
    id: '8',
    name: 'IA para Desenvolvedores',
    slug: 'ia-devs',
    level: 8,
    description: 'Domine IA aplicada: LLMs, RAG, MCP, Agentes',
    icon: '🤖',
    color: '#f97316',
    totalModules: 6,
    totalLessons: 50,
    totalExercises: 55,
    estimatedHours: 100,
    difficulty: 'advanced',
    progress: 0,
    status: 'locked',
    enrolled: false,
  },
  {
    id: '9',
    name: 'Staff Engineer',
    slug: 'staff-engineer',
    level: 9,
    description: 'Competências de Staff/Principal Engineer',
    icon: '👑',
    color: '#eab308',
    totalModules: 6,
    totalLessons: 55,
    totalExercises: 60,
    estimatedHours: 120,
    difficulty: 'expert',
    progress: 0,
    status: 'locked',
    enrolled: false,
  },
];

export const weeklyRanking = [
  { rank: 1, name: 'CodeNinja', avatar: null, xp: 1420, level: 25 },
  { rank: 2, name: 'GoMaster', avatar: null, xp: 1180, level: 22 },
  { rank: 3, name: 'DevHero', avatar: null, xp: 950, level: 20 },
  { rank: 4, name: 'ByteRunner', avatar: null, xp: 890, level: 18 },
  { rank: 5, name: 'StackLord', avatar: null, xp: 780, level: 17 },
  { rank: 6, name: 'CloudPilot', avatar: null, xp: 720, level: 16 },
  { rank: 7, name: 'Edimar', avatar: null, xp: 680, level: 12, isCurrentUser: true },
  { rank: 8, name: 'DataDragon', avatar: null, xp: 620, level: 14 },
  { rank: 9, name: 'AsyncKing', avatar: null, xp: 580, level: 13 },
  { rank: 10, name: 'BugHunter', avatar: null, xp: 540, level: 12 },
];

export const recentAchievements = [
  { id: '1', name: 'Week Warrior', description: 'Streak de 7 dias', icon: '📅', rarity: 'common', unlockedAt: '2026-06-14' },
  { id: '2', name: 'Clean Coder', description: '10 exercícios com score 90+', icon: '💎', rarity: 'rare', unlockedAt: '2026-06-12' },
  { id: '3', name: 'Scholar', description: 'Completar uma trilha inteira', icon: '🎓', rarity: 'epic', unlockedAt: '2026-06-10' },
];

export const allAchievements = [
  // Learning
  { id: '1', name: 'First Step', description: 'Completar primeira aula', icon: '🌱', rarity: 'common', category: 'learning', unlocked: true },
  { id: '2', name: 'Bookworm', description: 'Completar 50 aulas', icon: '📚', rarity: 'rare', category: 'learning', unlocked: true, progress: 68, target: 50 },
  { id: '3', name: 'Scholar', description: 'Completar uma trilha inteira', icon: '🎓', rarity: 'epic', category: 'learning', unlocked: true },
  { id: '4', name: 'Academy Graduate', description: 'Completar 5 trilhas', icon: '🏫', rarity: 'legendary', category: 'learning', unlocked: false, progress: 1, target: 5 },
  { id: '5', name: 'Galaxy Brain', description: 'Completar todas as trilhas', icon: '🌌', rarity: 'mythic', category: 'learning', unlocked: false, progress: 1, target: 10 },
  // Coding
  { id: '6', name: 'First Commit', description: 'Primeiro exercício entregue', icon: '⌨️', rarity: 'common', category: 'coding', unlocked: true },
  { id: '7', name: 'Clean Coder', description: '10 exercícios com score 90+', icon: '💎', rarity: 'rare', category: 'coding', unlocked: true, progress: 14, target: 10 },
  { id: '8', name: 'Perfect Score', description: 'Code review com score 100', icon: '🏆', rarity: 'epic', category: 'coding', unlocked: false, progress: 0, target: 1 },
  { id: '9', name: 'Code Machine', description: '100 exercícios completados', icon: '🔥', rarity: 'epic', category: 'coding', unlocked: false, progress: 87, target: 100 },
  { id: '10', name: 'Code Wizard', description: '50 exercícios com score 95+', icon: '🧙', rarity: 'legendary', category: 'coding', unlocked: false, progress: 8, target: 50 },
  // Consistency
  { id: '11', name: 'Week Warrior', description: 'Streak de 7 dias', icon: '📅', rarity: 'common', category: 'consistency', unlocked: true },
  { id: '12', name: 'Month Master', description: 'Streak de 30 dias', icon: '🗓️', rarity: 'rare', category: 'consistency', unlocked: false, progress: 15, target: 30 },
  { id: '13', name: 'Quarter Hero', description: 'Streak de 90 dias', icon: '📆', rarity: 'epic', category: 'consistency', unlocked: false, progress: 15, target: 90 },
  { id: '14', name: 'Year Legend', description: 'Streak de 365 dias', icon: '🎖️', rarity: 'legendary', category: 'consistency', unlocked: false, progress: 15, target: 365 },
  // Projects
  { id: '15', name: 'Builder', description: 'Primeiro projeto completo', icon: '🔨', rarity: 'common', category: 'projects', unlocked: true },
  { id: '16', name: 'Architect', description: 'Projeto com score arquitetura 90+', icon: '🏗️', rarity: 'rare', category: 'projects', unlocked: false, progress: 0, target: 1 },
  { id: '17', name: 'Deployer', description: 'Primeiro deploy bem-sucedido', icon: '🚀', rarity: 'rare', category: 'projects', unlocked: true },
];

export const userSkills = [
  { name: 'Go', level: 4, maxLevel: 10, xp: 1200, category: 'language' },
  { name: 'PostgreSQL', level: 3, maxLevel: 10, xp: 800, category: 'database' },
  { name: 'Docker', level: 2, maxLevel: 10, xp: 500, category: 'infrastructure' },
  { name: 'Git', level: 5, maxLevel: 10, xp: 1500, category: 'tools' },
  { name: 'Algorithms', level: 4, maxLevel: 10, xp: 1100, category: 'fundamentals' },
  { name: 'REST APIs', level: 3, maxLevel: 10, xp: 750, category: 'backend' },
  { name: 'Testing', level: 2, maxLevel: 10, xp: 400, category: 'quality' },
  { name: 'Linux', level: 4, maxLevel: 10, xp: 1000, category: 'infrastructure' },
  { name: 'Clean Code', level: 3, maxLevel: 10, xp: 700, category: 'quality' },
  { name: 'Data Structures', level: 4, maxLevel: 10, xp: 1050, category: 'fundamentals' },
];

export const exercises = [
  {
    id: '1',
    title: 'Implementar Busca Binária',
    difficulty: 'medium',
    language: 'go',
    xpReward: 30,
    tags: ['algorithms', 'binary_search'],
    estimatedMinutes: 20,
    completedByUser: true,
    userScore: 85,
  },
  {
    id: '2',
    title: 'Worker Pool com Goroutines',
    difficulty: 'hard',
    language: 'go',
    xpReward: 100,
    tags: ['concurrency', 'goroutines', 'channels'],
    estimatedMinutes: 45,
    completedByUser: false,
    userScore: null,
  },
  {
    id: '3',
    title: 'CRUD Handler com Clean Architecture',
    difficulty: 'medium',
    language: 'go',
    xpReward: 30,
    tags: ['clean_architecture', 'http', 'handlers'],
    estimatedMinutes: 30,
    completedByUser: true,
    userScore: 72,
  },
  {
    id: '4',
    title: 'Implementar Rate Limiter',
    difficulty: 'hard',
    language: 'go',
    xpReward: 100,
    tags: ['algorithms', 'rate_limiting', 'redis'],
    estimatedMinutes: 40,
    completedByUser: false,
    userScore: null,
  },
  {
    id: '5',
    title: 'Two Sum',
    difficulty: 'easy',
    language: 'go',
    xpReward: 10,
    tags: ['algorithms', 'hash_map'],
    estimatedMinutes: 10,
    completedByUser: true,
    userScore: 95,
  },
  {
    id: '6',
    title: 'Middleware de Autenticação JWT',
    difficulty: 'medium',
    language: 'go',
    xpReward: 30,
    tags: ['auth', 'jwt', 'middleware'],
    estimatedMinutes: 25,
    completedByUser: true,
    userScore: 78,
  },
  {
    id: '7',
    title: 'Event Sourcing Básico',
    difficulty: 'expert',
    language: 'go',
    xpReward: 300,
    tags: ['architecture', 'event_sourcing', 'cqrs'],
    estimatedMinutes: 90,
    completedByUser: false,
    userScore: null,
  },
  {
    id: '8',
    title: 'Implementar LRU Cache',
    difficulty: 'hard',
    language: 'go',
    xpReward: 100,
    tags: ['data_structures', 'cache', 'linked_list'],
    estimatedMinutes: 45,
    completedByUser: false,
    userScore: null,
  },
];

export const xpHistory = [
  { date: 'Seg', xp: 120 },
  { date: 'Ter', xp: 85 },
  { date: 'Qua', xp: 200 },
  { date: 'Qui', xp: 150 },
  { date: 'Sex', xp: 95 },
  { date: 'Sáb', xp: 180 },
  { date: 'Dom', xp: 60 },
];

export const activityHeatmap = Array.from({ length: 365 }, (_, i) => {
  const date = new Date(2026, 0, 1);
  date.setDate(date.getDate() + i);
  const contributions = Math.random() > 0.3 ? Math.floor(Math.random() * 8) : 0;
  return {
    date: date.toISOString().split('T')[0],
    contributions,
  };
});

export const weeklyGoals = [
  { id: '1', title: 'Completar Aula 3.4 — Middleware em Go', completed: true },
  { id: '2', title: 'Exercício: Implementar auth JWT', completed: true },
  { id: '3', title: 'Projeto: Endpoint POST /login', completed: false, progress: 70 },
  { id: '4', title: 'Quiz do Módulo 3', completed: false },
  { id: '5', title: '2 exercícios de revisão', completed: false },
];

export const levels = [
  { level: 1, title: 'Cadet', xpRequired: 0 },
  { level: 5, title: 'Astronaut', xpRequired: 1000 },
  { level: 10, title: 'Commander', xpRequired: 3000 },
  { level: 15, title: 'Captain', xpRequired: 6000 },
  { level: 20, title: 'Admiral', xpRequired: 10000 },
  { level: 25, title: 'Star Commander', xpRequired: 15000 },
  { level: 30, title: 'Galaxy Defender', xpRequired: 22000 },
  { level: 40, title: 'Constellation Lord', xpRequired: 40000 },
  { level: 50, title: 'Cosmic Architect', xpRequired: 75000 },
];

export const mentorMessages = [
  {
    id: '1',
    role: 'assistant' as const,
    content: 'Olá, Edimar! 👋 Eu sou o **Atlas**, seu mentor IA no DEV GALÁXIAS. Estou aqui para te acompanhar na sua jornada de desenvolvedor.\n\nVi que você está na trilha de **Go Básico** e acabou de começar o módulo de concorrência. Quer que eu te ajude com goroutines e channels?',
    timestamp: '2026-06-15T08:00:00Z',
  },
  {
    id: '2',
    role: 'user' as const,
    content: 'Sim! Estou com dificuldade pra entender channels. Qual a diferença entre buffered e unbuffered?',
    timestamp: '2026-06-15T08:01:00Z',
  },
  {
    id: '3',
    role: 'assistant' as const,
    content: 'Ótima pergunta! Antes de eu explicar, deixa eu te fazer uma pergunta pra pensar:\n\n🤔 Imagine que você está numa fila de banco. Existem duas situações:\n\n1. **Fila sem cadeiras** (unbuffered): Você só pode entrar na fila quando o caixa está pronto pra te atender. Se o caixa está ocupado, você fica bloqueado esperando.\n\n2. **Fila com cadeiras** (buffered): Existem cadeiras onde você pode sentar e esperar. Você só fica bloqueado se todas as cadeiras estiverem ocupadas.\n\nAgora, tentando traduzir isso para código Go:\n\n```go\n// Unbuffered — bloqueia até alguém receber\nch := make(chan int)\n\n// Buffered — bloqueia só quando o buffer está cheio\nch := make(chan int, 5)\n```\n\nCom essa analogia em mente, você consegue pensar em **quando usaria** cada um? 🎯',
    timestamp: '2026-06-15T08:02:00Z',
  },
];
